### ISSUE TITLE
After using MacOS Utilities to reinstall macOS

### ISSUE THREAD

**Issue by Ziotic21** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#6]
Hi,

After using macOS Utilities to reinstall macOS it takes 15-20minutes to download then it reboots but nothing happens if I check opencore like the attached pictures. Any help would be appreciated :)

![240116892_2173356202963975_4117989605959862471_n](https://user-images.githubusercontent.com/89620124/131060913-47e93dbd-3a6b-4c2f-bb5f-74c687e8ba0d.jpg)
![240483173_536322084301811_2776149243087112781_n](https://user-images.githubusercontent.com/89620124/131060916-5dd1dee7-25af-4b48-be9a-f50cb8785265.jpg)

**Comment by Innoxious** [comment]
Hi @Ziotic21, is this your first time installing with OpenCore? I'm trying to figure out what stage of the installation process you're in because you shouldn't need to **re**-install at any point?

Have a read of this if you want to start from scratch: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/
