### ISSUE TITLE
Touchscreen ?

### ISSUE THREAD

**Issue by gityasss** [Innoxious/hackintosh-hp-840-g3-intel-ac8260#9]
Hi innoxious
I have the same config laptop as yours and was wondering if the touchscreen works under Big sur ?
Have a good day

**Comment by Innoxious** [comment]
Hey @gityasss, I am unable to test if the touchscreen would work because my laptop doesn't have that feature. It _might_ work through the https://github.com/VoodooI2C/VoodooI2C kext which is included in my EFI.

Generally speaking through, Mac OS isn't built for touch screens so consider if you really need it in your hackintosh 😛 

Do come back and leave a comment if it works though!

Cheers
